### ISSUE TITLE
Unexpected theme comment in `index.theme`

### ISSUE THREAD

**Issue by murlakatamenka** [CachyOS/CachyOS-Nord-KDE#2]
https://github.com/CachyOS/CachyOS-Nord-KDE/blob/18b15354072ba012e2885422b135d146a32ee0f7/gtk/themes/cachyOS-nord/index.theme#L4

> Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).

**Comment by ddh4r4m** [comment]
This is fixed.
